"""
AST-based static validation for AI-generated Manim code.

Nothing generated by Gemini is ever executed via eval/exec inside this
process, and nothing is ever run through a shell. This module only
*inspects* the code textually/structurally; the actual render happens
in manim_runner.py via a fixed subprocess argument list against a
Python file that has passed this validation.
"""
from __future__ import annotations

import ast
from dataclasses import dataclass, field

# Modules the generated code is allowed to import.
ALLOWED_MODULES: set[str] = {
    "manim",
    "numpy",
    "math",
    "cmath",
    "random",
    "itertools",
    "functools",
    "colour",
    "dataclasses",
    "typing",
    "fractions",
    "decimal",
}

# Anything starting with these prefixes is allowed (submodules of manim/numpy).
ALLOWED_PREFIXES: tuple[str, ...] = ("manim.", "numpy.")

# Explicitly forbidden regardless of anything else.
FORBIDDEN_MODULES: set[str] = {
    "os",
    "sys",
    "subprocess",
    "shutil",
    "socket",
    "requests",
    "urllib",
    "urllib2",
    "http",
    "ftplib",
    "pathlib",
    "io",
    "multiprocessing",
    "threading",
    "ctypes",
    "importlib",
    "pickle",
    "shelve",
    "sqlite3",
    "asyncio",
    "webbrowser",
    "platform",
    "pty",
    "signal",
    "resource",
    "tempfile",
    "glob",
}

FORBIDDEN_CALL_NAMES: set[str] = {
    "eval",
    "exec",
    "compile",
    "open",
    "__import__",
    "input",
    "exit",
    "quit",
    "breakpoint",
    "globals",
    "locals",
    "vars",
    "getattr",  # blocked to prevent attribute-based sandbox escapes
    "setattr",
    "delattr",
}

# Dunder attribute access is a classic sandbox-escape vector.
FORBIDDEN_ATTR_PREFIXES = ("__",)

MAX_CODE_LENGTH = 60_000  # characters, generous but bounded


@dataclass
class ValidationResult:
    ok: bool
    errors: list[str] = field(default_factory=list)
    scene_class_names: list[str] = field(default_factory=list)


def _module_root(name: str) -> str:
    return name.split(".")[0]


def _is_allowed_module(name: str) -> bool:
    if name in ALLOWED_MODULES:
        return True
    return any(name.startswith(p) for p in ALLOWED_PREFIXES)


def validate_manim_code(code: str) -> ValidationResult:
    errors: list[str] = []

    if not code or not code.strip():
        return ValidationResult(ok=False, errors=["Generated code is empty."])

    if len(code) > MAX_CODE_LENGTH:
        return ValidationResult(ok=False, errors=["Generated code exceeds maximum allowed length."])

    # Reject obvious shell/string-based escape attempts before even parsing.
    lowered = code.lower()
    for token in ("os.system", "subprocess.", "shutil.", "__import__", "eval(", "exec(", "compile("):
        if token in lowered:
            errors.append(f"Forbidden pattern detected: '{token}'")

    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        return ValidationResult(ok=False, errors=[f"Syntax error in generated code: {e}"])

    scene_classes: list[str] = []

    class Visitor(ast.NodeVisitor):
        def visit_Import(self, node: ast.Import) -> None:  # noqa: N802
            for alias in node.names:
                root = _module_root(alias.name)
                if root in FORBIDDEN_MODULES:
                    errors.append(f"Import of forbidden module '{alias.name}' is not allowed.")
                elif not _is_allowed_module(alias.name) and not _is_allowed_module(root):
                    errors.append(f"Import of non-whitelisted module '{alias.name}'.")
            self.generic_visit(node)

        def visit_ImportFrom(self, node: ast.ImportFrom) -> None:  # noqa: N802
            mod = node.module or ""
            root = _module_root(mod)
            if root in FORBIDDEN_MODULES:
                errors.append(f"Import from forbidden module '{mod}' is not allowed.")
            elif not _is_allowed_module(mod) and not _is_allowed_module(root):
                errors.append(f"Import from non-whitelisted module '{mod}'.")
            self.generic_visit(node)

        def visit_Call(self, node: ast.Call) -> None:  # noqa: N802
            fn = node.func
            name = None
            if isinstance(fn, ast.Name):
                name = fn.id
            elif isinstance(fn, ast.Attribute):
                name = fn.attr
            if name in FORBIDDEN_CALL_NAMES:
                errors.append(f"Use of forbidden call '{name}(...)' is not allowed.")
            self.generic_visit(node)

        def visit_Attribute(self, node: ast.Attribute) -> None:  # noqa: N802
            if node.attr.startswith(FORBIDDEN_ATTR_PREFIXES):
                errors.append(f"Access to dunder attribute '{node.attr}' is not allowed.")
            self.generic_visit(node)

        def visit_ClassDef(self, node: ast.ClassDef) -> None:  # noqa: N802
            base_names = []
            for b in node.bases:
                if isinstance(b, ast.Name):
                    base_names.append(b.id)
                elif isinstance(b, ast.Attribute):
                    base_names.append(b.attr)
            if any(b in ("Scene", "ThreeDScene", "MovingCameraScene", "ZoomedScene") for b in base_names):
                scene_classes.append(node.name)
            self.generic_visit(node)

        def visit_With(self, node: ast.With) -> None:  # noqa: N802
            self.generic_visit(node)

    Visitor().visit(tree)

    if not scene_classes:
        errors.append("No Manim Scene subclass found in generated code.")
    elif len(scene_classes) > 1:
        # Not fatal, but we only ever render the first one; warn via error list
        # kept informational rather than blocking.
        pass

    return ValidationResult(ok=len(errors) == 0, errors=errors, scene_class_names=scene_classes)
